services:
  rag-api:
    build: .
    container_name: rag-agent-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data/chroma_db
      - ./logs:/data/logs
      - C:\Users\inervers\Desktop\OH-WorkSpace\dl-learning\hf_cache:/root/.cache/huggingface
      - C:\Users\inervers\Desktop\OH-WorkSpace\rag-advanced\models\cross-encoder:/app/models/cross-encoder
    env_file:
      - .env
    environment:
      - RAG_CHROMA_DIR=/data/chroma_db
      - RAG_LOG_FILE=/data/logs/rag_api.log
      - HF_HOME=/root/.cache/huggingface
      - HF_HUB_DISABLE_SYMLINKS=1

volumes:
  chroma_data:
